version: '2'
services:
  micro-app:
    image: micro
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://micro-mssql:1433;database=micro
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  micro-mssql:
    extends:
      file: mssql.yml
      service: micro-mssql
